# Generated by Django 4.1.3 on 2022-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newsstory_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsstory",
            name="image_url",
            field=models.TextField(default=""),
        ),
    ]
